// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

export const Images = z.object({
  original: z.string(),
  small: z.string(),
  medium: z.string(),
  large: z.string(),
});
export type Images = z.infer<typeof Images>;

export const Artist = z.object({
  id: z.string(),
  name: z.string(),
  picture: Images,
  created: z.number(),
  updated: z.number(),
});
export type Artist = z.infer<typeof Artist>;

export const GetArtists = z.object({
  artists: z.array(Artist),
});
export type GetArtists = z.infer<typeof GetArtists>;

export const GetArtistById = Artist;
export type GetArtistById = z.infer<typeof GetArtistById>;

export const Album = z.object({
  id: z.string(),
  name: z.string(),
  coverArt: Images,
  artistId: z.string(),
  artistName: z.string(),
  year: z.number().nullable(),
  created: z.number(),
  updated: z.number(),
});
export type Album = z.infer<typeof Album>;

export const GetArtistAlbumsById = z.object({
  albums: z.array(Album),
});
export type GetArtistAlbumsById = z.infer<typeof GetArtistAlbumsById>;

export const EditArtistBody = z.object({
  name: z.string().nullable(),
});
export type EditArtistBody = z.infer<typeof EditArtistBody>;

export const GetAlbums = z.object({
  albums: z.array(Album),
});
export type GetAlbums = z.infer<typeof GetAlbums>;

export const GetAlbumById = Album;
export type GetAlbumById = z.infer<typeof GetAlbumById>;

export const Track = z.object({
  id: z.string(),
  name: z.string(),
  albumId: z.string(),
  artistId: z.string(),
  number: z.number().nullable(),
  duration: z.number().nullable(),
  year: z.number().nullable(),
  originalMediaUrl: z.string(),
  mobileMediaUrl: z.string(),
  coverArt: Images,
  albumName: z.string(),
  artistName: z.string(),
  created: z.number(),
  updated: z.number(),
  tags: z.array(z.string()),
});
export type Track = z.infer<typeof Track>;

export const GetAlbumTracks = z.object({
  tracks: z.array(Track),
});
export type GetAlbumTracks = z.infer<typeof GetAlbumTracks>;

export const EditAlbumBody = z.object({
  name: z.string().nullable(),
  artistId: z.string().nullable(),
  artistName: z.string().nullable(),
  year: z.number().nullable(),
});
export type EditAlbumBody = z.infer<typeof EditAlbumBody>;

export const CreateAlbum = z.object({
  albumId: z.string(),
});
export type CreateAlbum = z.infer<typeof CreateAlbum>;

export const CreateAlbumBody = z.object({
  name: z.string(),
  artist: z.string(),
});
export type CreateAlbumBody = z.infer<typeof CreateAlbumBody>;

export const UploadTracksBody = z.object({
  forceExtractNumber: z.boolean(),
});
export type UploadTracksBody = z.infer<typeof UploadTracksBody>;

export const Page = z.object({
  page: z.number(),
  perPage: z.number(),
  totalItems: z.number(),
  totalPages: z.number(),
});
export type Page = z.infer<typeof Page>;

export const GetTracks = z.object({
  page: Page,
  tracks: z.array(Track),
});
export type GetTracks = z.infer<typeof GetTracks>;

export const GetTrackById = Track;
export type GetTrackById = z.infer<typeof GetTrackById>;

export const EditTrackBody = z.object({
  name: z.string().nullable().optional(),
  artistId: z.string().nullable().optional(),
  artistName: z.string().nullable().optional(),
  year: z.number().nullable().optional(),
  number: z.number().nullable().optional(),
  tags: z.array(z.string()).nullable().optional(),
});
export type EditTrackBody = z.infer<typeof EditTrackBody>;

export const Signup = z.object({
  id: z.string(),
  username: z.string(),
});
export type Signup = z.infer<typeof Signup>;

export const SignupBody = z.object({
  username: z.string(),
  password: z.string(),
  passwordConfirm: z.string(),
});
export type SignupBody = z.infer<typeof SignupBody>;

export const Signin = z.object({
  token: z.string(),
});
export type Signin = z.infer<typeof Signin>;

export const SigninBody = z.object({
  username: z.string(),
  password: z.string(),
});
export type SigninBody = z.infer<typeof SigninBody>;

export const ChangePasswordBody = z.object({
  currentPassword: z.string(),
  newPassword: z.string(),
  newPasswordConfirm: z.string(),
});
export type ChangePasswordBody = z.infer<typeof ChangePasswordBody>;

export const GetMe = z.object({
  id: z.string(),
  username: z.string(),
  isOwner: z.boolean(),
});
export type GetMe = z.infer<typeof GetMe>;

export const Playlist = z.object({
  id: z.string(),
  name: z.string(),
});
export type Playlist = z.infer<typeof Playlist>;

export const GetPlaylists = z.object({
  playlists: z.array(Playlist),
});
export type GetPlaylists = z.infer<typeof GetPlaylists>;

export const CreatePlaylist = Playlist;
export type CreatePlaylist = z.infer<typeof CreatePlaylist>;

export const CreatePlaylistBody = z.object({
  name: z.string(),
});
export type CreatePlaylistBody = z.infer<typeof CreatePlaylistBody>;

export const PostPlaylistFilterBody = z.object({
  name: z.string(),
  filter: z.string(),
  sort: z.string(),
});
export type PostPlaylistFilterBody = z.infer<typeof PostPlaylistFilterBody>;

export const GetPlaylistById = z.object({
  id: z.string(),
  name: z.string(),
  items: z.array(Track),
});
export type GetPlaylistById = z.infer<typeof GetPlaylistById>;

export const AddItemsToPlaylistBody = z.object({
  tracks: z.array(z.string()),
});
export type AddItemsToPlaylistBody = z.infer<typeof AddItemsToPlaylistBody>;

export const DeletePlaylistItemsBody = z.object({
  trackIds: z.array(z.string()),
});
export type DeletePlaylistItemsBody = z.infer<typeof DeletePlaylistItemsBody>;

export const MovePlaylistItemBody = z.object({
  trackId: z.string(),
  toIndex: z.number(),
});
export type MovePlaylistItemBody = z.infer<typeof MovePlaylistItemBody>;

export const GetSystemInfo = z.object({
  version: z.string(),
});
export type GetSystemInfo = z.infer<typeof GetSystemInfo>;

export const ExportArtist = z.object({
  id: z.string(),
  name: z.string(),
  picture: z.string(),
});
export type ExportArtist = z.infer<typeof ExportArtist>;

export const ExportAlbum = z.object({
  id: z.string(),
  name: z.string(),
  artistId: z.string(),
  coverArt: z.string(),
  year: z.number(),
});
export type ExportAlbum = z.infer<typeof ExportAlbum>;

export const ExportTrack = z.object({
  id: z.string(),
  name: z.string(),
  albumId: z.string(),
  artistId: z.string(),
  number: z.number(),
  duration: z.number(),
  year: z.number(),
  exportName: z.string(),
  originalFilename: z.string(),
  mobileFilename: z.string(),
  created: z.number(),
  tags: z.array(z.string()),
});
export type ExportTrack = z.infer<typeof ExportTrack>;

export const Export = z.object({
  artists: z.array(ExportArtist),
  albums: z.array(ExportAlbum),
  tracks: z.array(ExportTrack),
});
export type Export = z.infer<typeof Export>;

export const Taglist = z.object({
  id: z.string(),
  name: z.string(),
  filter: z.string(),
  created: z.number(),
  updated: z.number(),
});
export type Taglist = z.infer<typeof Taglist>;

export const GetTaglists = z.object({
  taglists: z.array(Taglist),
});
export type GetTaglists = z.infer<typeof GetTaglists>;

export const GetTaglistById = Taglist;
export type GetTaglistById = z.infer<typeof GetTaglistById>;

export const GetTaglistTracks = z.object({
  page: Page,
  tracks: z.array(Track),
});
export type GetTaglistTracks = z.infer<typeof GetTaglistTracks>;

export const CreateTaglist = z.object({
  id: z.string(),
});
export type CreateTaglist = z.infer<typeof CreateTaglist>;

export const CreateTaglistBody = z.object({
  name: z.string(),
  filter: z.string(),
});
export type CreateTaglistBody = z.infer<typeof CreateTaglistBody>;

export const UpdateTaglistBody = z.object({
  name: z.string().nullable().optional(),
  filter: z.string().nullable().optional(),
});
export type UpdateTaglistBody = z.infer<typeof UpdateTaglistBody>;

