// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	CoverArt pgtype.Text `json:"coverArt"`
	ArtistID string      `json:"artistId"`
}

type Artist struct {
	ID      string      `json:"id"`
	Name    string      `json:"name"`
	Picture pgtype.Text `json:"picture"`
}

type Track struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	CoverArt pgtype.Text `json:"coverArt"`
	AlbumID  string      `json:"albumId"`
	ArtistID string      `json:"artistId"`
}
