// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: tracks.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrack = `-- name: CreateTrack :exec
INSERT INTO tracks (id, track_number, name, cover_art, album_id, artist_id) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTrackParams struct {
	ID          string      `json:"id"`
	TrackNumber int32       `json:"trackNumber"`
	Name        string      `json:"name"`
	CoverArt    pgtype.Text `json:"coverArt"`
	AlbumID     string      `json:"albumId"`
	ArtistID    string      `json:"artistId"`
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) error {
	_, err := q.db.Exec(ctx, createTrack,
		arg.ID,
		arg.TrackNumber,
		arg.Name,
		arg.CoverArt,
		arg.AlbumID,
		arg.ArtistID,
	)
	return err
}

const deleteAllTracks = `-- name: DeleteAllTracks :exec
DELETE FROM tracks
`

func (q *Queries) DeleteAllTracks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllTracks)
	return err
}

const getAllTracks = `-- name: GetAllTracks :many
SELECT id, track_number, name, cover_art, album_id, artist_id FROM tracks
`

func (q *Queries) GetAllTracks(ctx context.Context) ([]Track, error) {
	rows, err := q.db.Query(ctx, getAllTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Track{}
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.TrackNumber,
			&i.Name,
			&i.CoverArt,
			&i.AlbumID,
			&i.ArtistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrack = `-- name: GetTrack :one
SELECT id, track_number, name, cover_art, album_id, artist_id FROM tracks WHERE id=$1
`

func (q *Queries) GetTrack(ctx context.Context, id string) (Track, error) {
	row := q.db.QueryRow(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.TrackNumber,
		&i.Name,
		&i.CoverArt,
		&i.AlbumID,
		&i.ArtistID,
	)
	return i, err
}

const getTracksByAlbum = `-- name: GetTracksByAlbum :many
SELECT id, track_number, name, cover_art, album_id, artist_id FROM tracks WHERE album_id=$1 ORDER BY track_number
`

func (q *Queries) GetTracksByAlbum(ctx context.Context, albumID string) ([]Track, error) {
	rows, err := q.db.Query(ctx, getTracksByAlbum, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Track{}
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.TrackNumber,
			&i.Name,
			&i.CoverArt,
			&i.AlbumID,
			&i.ArtistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
