// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: albums.sql

package database

import (
	"context"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (id, name, cover_art, artist_id) VALUES ($1, $2, $3, $4) RETURNING id, name, cover_art, artist_id
`

type CreateAlbumParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	CoverArt string `json:"coverArt"`
	ArtistID string `json:"artistId"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.ID,
		arg.Name,
		arg.CoverArt,
		arg.ArtistID,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CoverArt,
		&i.ArtistID,
	)
	return i, err
}

const deleteAllAlbums = `-- name: DeleteAllAlbums :exec
DELETE FROM albums
`

func (q *Queries) DeleteAllAlbums(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllAlbums)
	return err
}

const getAlbum = `-- name: GetAlbum :one
SELECT id, name, cover_art, artist_id FROM albums WHERE id=$1
`

func (q *Queries) GetAlbum(ctx context.Context, id string) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbum, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CoverArt,
		&i.ArtistID,
	)
	return i, err
}

const getAlbumsByArtist = `-- name: GetAlbumsByArtist :many
SELECT id, name, cover_art, artist_id FROM albums WHERE artist_id=$1
`

func (q *Queries) GetAlbumsByArtist(ctx context.Context, artistID string) ([]Album, error) {
	rows, err := q.db.Query(ctx, getAlbumsByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Album{}
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CoverArt,
			&i.ArtistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAlbums = `-- name: GetAllAlbums :many
SELECT id, name, cover_art, artist_id FROM albums
`

func (q *Queries) GetAllAlbums(ctx context.Context) ([]Album, error) {
	rows, err := q.db.Query(ctx, getAllAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Album{}
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CoverArt,
			&i.ArtistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
