// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type Album struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	CoverArt string `json:"coverArt"`
	ArtistID string `json:"artistId"`
	Path     string `json:"path"`
}

type Artist struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Picture string `json:"picture"`
	Path    string `json:"path"`
}

type Track struct {
	ID                string `json:"id"`
	TrackNumber       int32  `json:"trackNumber"`
	Name              string `json:"name"`
	CoverArt          string `json:"coverArt"`
	Path              string `json:"path"`
	BestQualityFile   string `json:"bestQualityFile"`
	MobileQualityFile string `json:"mobileQualityFile"`
	AlbumID           string `json:"albumId"`
	ArtistID          string `json:"artistId"`
}
