// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/albums": {
            "get": {
                "description": "Get all albums",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "albums"
                ],
                "summary": "Get all albums",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse-types_ApiGetAlbumsData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new album",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "albums"
                ],
                "summary": "Create new album",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Album name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Artist Id",
                        "name": "artistId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse-types_ApiPostAlbumData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        },
        "/albums/{id}": {
            "get": {
                "description": "Get album by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "albums"
                ],
                "summary": "Get album by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Album Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse-types_ApiGetAlbumByIdData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        },
        "/albums/{id}/tracks": {
            "get": {
                "description": "Get all tracks from album",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "albums"
                ],
                "summary": "Get all tracks from album",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Artist Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse-types_ApiGetAlbumTracksByIdData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        },
        "/artists": {
            "get": {
                "description": "Get all artists",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artists"
                ],
                "summary": "Get all artists",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse-types_ApiGetArtistsData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new artist",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artists"
                ],
                "summary": "Create new artist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Artist name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse-types_ApiPostArtistData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        },
        "/artists/{id}": {
            "get": {
                "description": "Get artist by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artists"
                ],
                "summary": "Get artist by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Artist Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse-types_ApiGetArtistByIdData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        },
        "/artists/{id}/albums": {
            "get": {
                "description": "Get all albums by artist",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artists"
                ],
                "summary": "Get all albums by artist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Artist Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse-types_ApiGetArtistAlbumsByIdData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        },
        "/tracks": {
            "get": {
                "description": "Get all tracks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tracks"
                ],
                "summary": "Get all tracks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse-types_ApiGetTracksData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new track",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tracks"
                ],
                "summary": "Create new track",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Track name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Track number",
                        "name": "number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Album Id",
                        "name": "albumId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Artist Id",
                        "name": "artistId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Best Quality File",
                        "name": "bestQualityFile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Mobile Quality File",
                        "name": "mobileQualityFile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Cover Art",
                        "name": "coverArt",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse-types_ApiPostTrackData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        },
        "/tracks/{id}": {
            "get": {
                "description": "Get track by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tracks"
                ],
                "summary": "Get track by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Track Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse-types_ApiGetTrackByIdData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.ApiAlbum": {
            "type": "object",
            "properties": {
                "artistId": {
                    "type": "string"
                },
                "coverArt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "types.ApiArtist": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                }
            }
        },
        "types.ApiError": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "types.ApiGetAlbumByIdData": {
            "type": "object",
            "properties": {
                "artistId": {
                    "type": "string"
                },
                "coverArt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "types.ApiGetAlbumTracksByIdData": {
            "type": "object",
            "properties": {
                "tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ApiTrack"
                    }
                }
            }
        },
        "types.ApiGetAlbumsData": {
            "type": "object",
            "properties": {
                "albums": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ApiAlbum"
                    }
                }
            }
        },
        "types.ApiGetArtistAlbumsByIdData": {
            "type": "object",
            "properties": {
                "albums": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ApiAlbum"
                    }
                }
            }
        },
        "types.ApiGetArtistByIdData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                }
            }
        },
        "types.ApiGetArtistsData": {
            "type": "object",
            "properties": {
                "artists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ApiArtist"
                    }
                }
            }
        },
        "types.ApiGetTrackByIdData": {
            "type": "object",
            "properties": {
                "albumId": {
                    "type": "string"
                },
                "artistId": {
                    "type": "string"
                },
                "bestQualityFile": {
                    "type": "string"
                },
                "coverArt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mobileQualityFile": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                }
            }
        },
        "types.ApiGetTracksData": {
            "type": "object",
            "properties": {
                "tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ApiGetTracksDataTrackItem"
                    }
                }
            }
        },
        "types.ApiGetTracksDataTrackItem": {
            "type": "object",
            "properties": {
                "albumId": {
                    "type": "string"
                },
                "albumName": {
                    "type": "string"
                },
                "artistId": {
                    "type": "string"
                },
                "artistName": {
                    "type": "string"
                },
                "bestQualityFile": {
                    "type": "string"
                },
                "coverArt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mobileQualityFile": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                }
            }
        },
        "types.ApiPostAlbumData": {
            "type": "object",
            "properties": {
                "artistId": {
                    "type": "string"
                },
                "coverArt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "types.ApiPostArtistData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                }
            }
        },
        "types.ApiPostTrackData": {
            "type": "object",
            "properties": {
                "albumId": {
                    "type": "string"
                },
                "artistId": {
                    "type": "string"
                },
                "bestQualityFile": {
                    "type": "string"
                },
                "coverArt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mobileQualityFile": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                }
            }
        },
        "types.ApiResponse-types_ApiGetAlbumByIdData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ApiGetAlbumByIdData"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "types.ApiResponse-types_ApiGetAlbumTracksByIdData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ApiGetAlbumTracksByIdData"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "types.ApiResponse-types_ApiGetAlbumsData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ApiGetAlbumsData"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "types.ApiResponse-types_ApiGetArtistAlbumsByIdData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ApiGetArtistAlbumsByIdData"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "types.ApiResponse-types_ApiGetArtistByIdData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ApiGetArtistByIdData"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "types.ApiResponse-types_ApiGetArtistsData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ApiGetArtistsData"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "types.ApiResponse-types_ApiGetTrackByIdData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ApiGetTrackByIdData"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "types.ApiResponse-types_ApiGetTracksData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ApiGetTracksData"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "types.ApiResponse-types_ApiPostAlbumData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ApiPostAlbumData"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "types.ApiResponse-types_ApiPostArtistData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ApiPostArtistData"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "types.ApiResponse-types_ApiPostTrackData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ApiPostTrackData"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "types.ApiTrack": {
            "type": "object",
            "properties": {
                "albumId": {
                    "type": "string"
                },
                "artistId": {
                    "type": "string"
                },
                "bestQualityFile": {
                    "type": "string"
                },
                "coverArt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mobileQualityFile": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Testing Testing",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
