basePath: /api/v1
definitions:
  types.ApiArtist:
    properties:
      id:
        type: string
      name:
        type: string
      picture:
        type: string
    type: object
  types.ApiError:
    properties:
      data: {}
      message:
        type: string
      status:
        example: 400
        type: integer
    type: object
  types.ApiResponse-types_ApiArtist:
    properties:
      data:
        $ref: '#/definitions/types.ApiArtist'
      status:
        example: 200
        type: integer
    type: object
info:
  contact: {}
  title: Testing Testing
paths:
  /artists:
    get:
      consumes:
      - application/json
      - text/xml
      description: Get all artists
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ApiResponse-types_ApiArtist'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ApiError'
      summary: Get all artists
      tags:
      - accounts
    post:
      consumes:
      - multipart/form-data
      description: Get all artists
      parameters:
      - description: Artist name
        in: formData
        name: name
        required: true
        type: string
      - description: Picture
        in: formData
        name: picture
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ApiResponse-types_ApiArtist'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ApiError'
      summary: Get all artists
      tags:
      - accounts
swagger: "2.0"
